export enum ClaimStatus {
  PENDING = 'PENDING',
  PENDING_COMPLETION = 'PENDING_COMPLETION',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  APPROVAL_DENIED = 'APPROVAL_DENIED',
  SUBMITTED = 'SUBMITTED',
  COMPLETED = 'COMPLETED',
  RESUBMITTED = 'RESUBMITTED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
}