export class FacilityUtilityConstants {
    static IMAGING_ADD_SUCCESS: string = 'Imaging Added!'
    static IMAGING_UPDATE_SUCCESS: string = 'Imaging Updated!'
    static IMAGING_DELETE_SUCCESS: string = 'Imaging Deleted!'
    static LAB_ADD_SUCCESS: string = 'Lab Added!'
    static LAB_UPDATE_SUCCESS: string = 'Lab Updated!'
    static LAB_DELETE_SUCCESS: string = 'Lab Deleted!'
    static SERIVCE_ADD_SUCCESS: string = 'Service Added!'
    static SERIVCE_UPDATE_SUCCESS: string = 'Service Updated!'
    static SERIVCE_DELETE_SUCCESS: string = 'Service Deleted!'
    static PRODUCT_ADD_SUCCESS: string = 'Product Added!'
    static PRODUCT_UPDATE_SUCCESS: string = 'Product Updated!'
    static PRODUCT_DELETE_SUCCESS: string = 'Product Deleted!'
    static PROCEDURE_ADD_SUCCESS: string = 'Procedure Added!'
    static PROCEDURE_DELETE_SUCCESS: string = 'Procedure Deleted!'
    static PROCEDURE_UPDATE_SUCCESS: string = 'Procedure Updated!'
    static DRUG_ADD_SUCCESS: string = 'Drug Added!'
    static DRUG_DELETE_SUCCESS: string = 'Drug Deleted!'
    static DRUG_UPDATE_SUCCESS: string = 'Drug Updated!'
}