export enum FileUploadStatus {
  UPLOADING = 'UPLOADING',
  UPLOADED = 'UPLOADED',
  EXECUTING = 'EXECUTING',
  COMPLETED = 'COMPLETED',
  PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED',
  FAILED = 'FAILED',
  DELETING = 'DELETING',
  PURGING = 'PURGING',
  DELETION_FAILED = 'DELETION_FAILED'
}