export enum HistoryTypes {
    MEDICAL_HISTORY = "MEDICAL_HISTORY",
    SOCIAL_HISTORY = "SOCIAL_HISTORY",
    ALLERGIC_HISTORY = "ALLERGIC_HISTORY",
    DRUG_HISTORY = "DRUG_HISTORY",
    FAMILY_HISTORY = "FAMILY_HISTORY",
    PSYCHOLOGICAL_HISTORY = "PSYCHOLOGICAL_HISTORY",
    SURGICAL_HISTORY = "SURGICAL_HISTORY"
}