export enum Roles {
    ADMIN = 'ADMIN',
    MANAGER = 'MANAGER',
    STAFF = 'STAFF',
    ACCOUNTANT = 'ACCOUNTANT',
    DOCTOR = 'DOCTOR',
    RECEPTIONIST = 'RECEPTIONIST',
    INSURANCE_COORDINATOR = 'INSURANCE_COORDINATOR'
}