export enum UtilityType {
    PROCEDURE = 'PROCEDURE',
    LAB = 'LAB',
    IMAGING = 'IMAGING',
    SERVICES_AND_PRODUCTS = 'PRODUCT_AND_SERVICES',
    DIAGNOSIS = 'DIAGNOSIS',
    PRESCRIPTION = 'PRESCRIPTION',
    DRUG = 'DRUG'
}