export enum UtilityTypeLabel {
    PROCEDURE = 'PROCEDURE',
    LAB = 'LAB',
    IMAGING = 'IMAGING',
    SERVICES_AND_PRODUCTS = 'SERVICES AND PRODUCT',
    DIAGNOSIS = 'DIAGNOSIS',
    PRESCRIPTION = 'PRESCRIPTION'
}